### ISSUE TITLE
Is it possible/convenient to output given number of sampling points a time without much total sampling points increase?

### ISSUE THREAD

**Issue by TangLaoya** [pradovera/greedy-loewner#2]
Dear Davide,

I have a new question: 
Is it possible/convenient to output given number of sampling points a time without much total sampling points increase?
Currently the iteration generate one sampling point a time, and I can't make use of the modern multiple cores CPUs, on the other hand, the most of time is spent by S parameter solving for the given frequencies. So I wish the iteration can generate multiple sampling points a time without increasing too much total sampling points.

Thanks,
Tang Laoya

**Comment by pradovera** [comment]
In the method I introduced [here](https://doi.org/10.1007/s10444-023-10091-7), only one new sample is added at each iteration. This step cannot be parallelized, since the estimator at each iteration is based on all previous samples.

However, there are three places where parallel computing might be incorporated in the algorithm:
- If the high-fidelity system is _not_ self-adjoint, i.e., if `is_system_selfadjoint=false`, then two samples are taken at each iteration, at `1j*z` and `-1j*z`. Those two evaluations can be parallelized.
- If the "batch" estimator is used, i.e., if `estimator_kind="lookaheadbatch"` and `batch_size>1`, then `batch_size` samples must be taken at each iteration for testing purposes. See Section 4.4 in [my paper](https://doi.org/10.1007/s10444-023-10091-7) for more information. Those `batch_size` evaluations can be parallelized.
- If the "random" estimator is used, i.e., if `estimator_kind="random"` and `batch_size>1`, then `batch_size` samples must be taken before the greedy iterations can start. (Those iterations are later used for testing purposes at each greedy iteration.) See Section 4.5 in [my paper](https://doi.org/10.1007/s10444-023-10091-7) for more information. Those `batch_size` evaluations can be parallelized.

That being said, it should be possible to extend the greedy Loewner Framework to take advantage of parallel computing, by adding more than one new sample point at each iteration. If you're interested in working on that, I encourage you to contact me by email (see [my webpage](https://pradovera.github.io/) for my contacts) :)

Davide

**Comment by TangLaoya** [comment]
Dear Davide,
Thank you very much for your kindly reply. I will study your papers and code carefully and ask you some questions by your email latter. Currently I implemented the AFS based on this [paper] (https://ieeexplore.ieee.org/abstract/document/10144544/). The curve fitting is implemented as you pointed in [Chebfun](https://www.chebfun.org/). But there are many unnecessary samples, so I noticed your paper and try to find whether the number of samples could be decreased or not.

Thanks,
Tang Laoya
